CREATE TABLE campaigns (
	id SERIAL PRIMARY KEY,
	name CHARACTER VARYING NOT NULL, 
	rows TEXT[] NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE,
	updated_at TIMESTAMP WITH TIME ZONE,
	deleted_at TIMESTAMP WITH TIME ZONE
);